[project]
name = "Echelon"
version = "0.1.0"
description = "Echelon is a monitoring daemon that watches specific line ranges in GitHub code and alerts you when they change."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.5",
]
